package Forms;

import DAO.LicenciaDAO;
import DAO.PersonaDAO;
import interfaces.ILicenciaDAO;
import interfaces.IPersonaDAO;
import dto.LicenciaDTO;
import dto.PersonaDTO;
import excepciones.PersistenciaException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.LicenciasNegocio;
import negocio.PersonasNegocio;
import recursos.DuracionLicencia;
import recursos.TipoLicencia;
import validaciones.Validadores;

/**
 *
 * @author Chris, bell y katt
 */
public class JLicenciaForm extends javax.swing.JFrame {

    private ILicenciaDAO licDao;
    private PersonaDTO personaDTO;
    private IPersonaDAO IperDao;
    private PersonaDAO perDao;
    private JMenu anterior;
    private LicenciaDTO lic;
    private DuracionLicencia duracion;
    private TipoLicencia tipo;
    private Validadores validadores;
    private PersonaDAO perDAO;
    private LicenciasNegocio licNeg;
    private PersonasNegocio perNeg;

    /**
     * Creates new form JLicenciaForm
     */
    public JLicenciaForm(JMenu anterior) {
        initComponents();
        this.licDao = new LicenciaDAO();
        this.perDao = new PersonaDAO();
        this.validadores = new Validadores();
        this.anterior = anterior;
        this.lic = new LicenciaDTO();
        this.personaDTO = new PersonaDTO();
        this.licNeg = new LicenciasNegocio();
        this.perNeg = new PersonasNegocio();
    }

    private void regresar() {
        this.anterior.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        azul = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        RFCBusqueda = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JToggleButton();
        botonRegresar5 = new javax.swing.JButton();
        cbVigencia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        chbDiscapacidad = new javax.swing.JCheckBox();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(20, 174, 92));

        azul.setBackground(new java.awt.Color(18, 234, 207));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setText("Módulo de Licencias");

        javax.swing.GroupLayout azulLayout = new javax.swing.GroupLayout(azul);
        azul.setLayout(azulLayout);
        azulLayout.setHorizontalGroup(
            azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(azulLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        azulLayout.setVerticalGroup(
            azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(azulLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        botonRegresar.setBackground(new java.awt.Color(117, 117, 117));
        botonRegresar.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        botonRegresar.setText(">");
        botonRegresar.setBorder(null);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel1.setText("RFC:");

        botonAceptar.setBackground(new java.awt.Color(175, 244, 198));
        botonAceptar.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        RFCBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFCBusquedaActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtNacimiento.setEditable(false);
        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        BtnBuscar.setBackground(new java.awt.Color(175, 244, 198));
        BtnBuscar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        BtnBuscar.setText("BUSCAR");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        botonRegresar5.setBackground(new java.awt.Color(117, 117, 117));
        botonRegresar5.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        botonRegresar5.setText(">");
        botonRegresar5.setBorder(null);
        botonRegresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar5ActionPerformed(evt);
            }
        });

        cbVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 años", "3 años" }));
        cbVigencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVigenciaItemStateChanged(evt);
            }
        });
        cbVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVigenciaActionPerformed(evt);
            }
        });

        jLabel3.setText("Vigencia:");

        chbDiscapacidad.setText("Discapacidad");
        chbDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDiscapacidadActionPerformed(evt);
            }
        });

        txtMonto.setEditable(false);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto:");

        txtRFC.setEditable(false);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(RFCBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnBuscar))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(botonRegresar5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275)
                        .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(fondoLayout.createSequentialGroup()
                                    .addComponent(cbVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chbDiscapacidad))
                                .addComponent(txtNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRFC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(botonRegresar))
                    .addComponent(botonRegresar5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RFCBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addGap(18, 18, 18)
                .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(chbDiscapacidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        JMenu me = new JMenu();
        me.setVisible(true);

        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        Calendar fechaEmision = Calendar.getInstance();
        lic = new LicenciaDTO(
                tipo,
                duracion,
                fechaEmision,
                getMonto(),
                personaDTO);
        try {
            licNeg.realizarTramite(lic);
            ValidacionExitosa validacionExitosa = new ValidacionExitosa();
            validacionExitosa.show();
            dispose();
        } catch (PersistenciaException ex) {
            Logger.getLogger(JLicenciaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        try {
            buscar();
        } catch (PersistenciaException ex) {
            Logger.getLogger(JLicenciaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void botonRegresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar5ActionPerformed
        JMenu m = new JMenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresar5ActionPerformed

    private void buscar() throws PersistenciaException {
        personaDTO = new PersonaDTO(RFCBusqueda.getText());
        String RFCb = RFCBusqueda.getText();
        if (RFCb.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor, ingrese el RFC para continuar",
                    "Error: Campo vacío",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (!validadores.validaRfc(RFCb)) {
            mostrarMensajeErrorFormatoRFC();
            return;
        }
        personaDTO = perNeg.consultarPersonaPorRfc(personaDTO);

        validarPersona();
    }

    private void mostrarMensajeErrorFormatoRFC() {
        JOptionPane.showMessageDialog(
                this,
                "RFC inválido. Verifica que el RFC sea \n el correcto e ingréselo nuevamente",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Método para mostrar un mensaje de error de persona no encontrada.
     */
    private void mostrarMensajeErrorNoEncontrado() {
        JOptionPane.showMessageDialog(
                this,
                "Persona no encontrada",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Método para validar una persona encontrada.
     */
    public void validarPersona() {
        if (personaDTO != null) {
            float monto = getMonto();
            String rfc = personaDTO.getRfc();
            String nombre = personaDTO.getNombre() + " " + personaDTO.getApellidoPaterno() + " " + personaDTO.getApellidoMaterno();
            String nacimiento = formatoFecha(personaDTO.getFechaNacimiento());
            String telefono = personaDTO.getTelefono();

            txtRFC.setText(rfc);
            txtNombre.setText(nombre);
            txtNacimiento.setText(nacimiento);
            txtTelefono.setText(telefono);
            txtMonto.setText(monto + "");

        } else {
            mostrarMensajeErrorNoEncontrado();
        }
    }

    private String formatoFecha(Calendar fecha) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date nacimiento = fecha.getTime();

        return formatter.format(nacimiento);
    }

    /**
     * Método para obtener el costo de la licencia.
     *
     * @return Costo de la licencia.
     */
    public float getMonto() {
        if (chbDiscapacidad.isSelected()) {
            tipo = TipoLicencia.discapacitado;
            switch (cbVigencia.getSelectedItem().toString()) {
                case "1 año":
                    duracion = DuracionLicencia.UnAnio;
                    break;
                case "2 años":
                    duracion = DuracionLicencia.dosAnios;
                    break;
                case "3 años":
                    duracion = DuracionLicencia.tresAnios;
                    break;
            }
            return duracion.getCostoDiscapacitado();
        } else {
            tipo = TipoLicencia.normal;
            switch (cbVigencia.getSelectedItem().toString()) {
                case "1 año":
                    duracion = DuracionLicencia.UnAnio;
                    break;
                case "2 años":
                    duracion = DuracionLicencia.dosAnios;
                    break;
                case "3 años":
                    duracion = DuracionLicencia.tresAnios;
                    break;
            }
            return duracion.getCostoNormal();
        }
    }

    private void cambiarEstadoCosto() {
        float monto = getMonto();
        txtMonto.setText(monto + "");
    }

    private void RFCBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFCBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFCBusquedaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVigenciaActionPerformed

    private void chbDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDiscapacidadActionPerformed
        cambiarEstadoCosto();
    }//GEN-LAST:event_chbDiscapacidadActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void cbVigenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVigenciaItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            cambiarEstadoCosto();
        }
    }//GEN-LAST:event_cbVigenciaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnBuscar;
    public javax.swing.JTextField RFCBusqueda;
    private javax.swing.JPanel azul;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonRegresar5;
    private javax.swing.JComboBox<String> cbVigencia;
    private javax.swing.JCheckBox chbDiscapacidad;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
