/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import dto.AutomovilDTO;
import dto.PlacaDTO;
import excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.PlacasNegocio;

/**
 *
 * @author Chris
 */
public class JTramitaPlaca extends javax.swing.JFrame {

    private AutomovilDTO autoDTO;
    private PlacaDTO placaDTO;
    private PlacasNegocio plaNeg;

    /**
     * Creates new form JTramitaPlaca
     */
    public JTramitaPlaca(PlacaDTO placaDTO) {
        initComponents();
        this.plaNeg = new PlacasNegocio();
        this.placaDTO = placaDTO;
        cargarDatos();
    }

    private void cargarDatos() {
        String tipoVehiculo;
        String numeroPlaca = plaNeg.generaPlacaNueva();
        String numeroFormateado;

        lblTipo.setText("Nuevo");
        plaNeg.calcularCostoVehiculoNuevo(placaDTO);
        placaDTO.setNumPlaca(numeroPlaca);
        autoDTO = placaDTO.getVehiculo();
        lblNumeroPlaca.setText(placaDTO.getNumPlaca());
        tipoVehiculo = placaDTO.getTipoVehiculo();
        numeroFormateado = String.format("%.2f", placaDTO.getMonto());

        lblColor.setText(autoDTO.getColor());
        lblLinea.setText(autoDTO.getLinea());
        lblModelo.setText(autoDTO.getModelo());
        lblMarca.setText(autoDTO.getMarca());
        lblNumeroSerie.setText(autoDTO.getNumSerie());

        lblCosto.setText("$" + numeroFormateado + " MXN");

        switch (tipoVehiculo) {
            case "Automovil":
                lblOpcion1.setText("Automóvil nuevo");
                lblOpcion2.setText("Automóvil usado");
                lblCosto1.setText("$1,500.00 MXN");
                lblCosto2.setText("$1,000.00 MXN");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroPlaca = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCostoPlacas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblOpcion1 = new javax.swing.JLabel();
        lblOpcion2 = new javax.swing.JLabel();
        lblCostos = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblCosto2 = new javax.swing.JLabel();
        lblCostoInfo = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        bRealizaTra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumeroPlaca.setText("Número de placa: ");

        lblNumeroSerie.setText("Número de serie:");

        lblMarca.setText("Marca:");

        lblLinea.setText("Linea:");

        lblModelo.setText("Modelo:");

        lblColor.setText("Color:");

        lblTipo.setText("Tipo:");

        jLabel8.setText("Resumen de el tramite de placa: ");

        lblCostoPlacas.setText("Costo total de placas:");

        jLabel10.setText("Estado de vehiculo:");

        lblOpcion1.setText("Automóvil nuevo:");

        lblOpcion2.setText("Automóvil usado:");

        lblCostos.setText("Costos:");

        lblCosto1.setText("$ 1,500.00 MXN");

        lblCosto2.setText("$ 1,000.00 MXN");

        lblCostoInfo.setText("Costo a pagar: ");

        lblCosto.setText("$ 1,500.00 MXN");

        bRealizaTra.setText("Realizar tramite");
        bRealizaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizaTraActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de placa: ");

        jLabel2.setText("Número de serie:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Linea:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Color:");

        jLabel7.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblNumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMarca)
                                .addComponent(lblNumeroSerie)
                                .addComponent(lblLinea)
                                .addComponent(lblModelo)
                                .addComponent(lblColor)
                                .addComponent(lblTipo)))
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostoPlacas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(lblOpcion1)
                                            .addComponent(lblOpcion2))
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblCostoInfo)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCosto2)
                                    .addComponent(lblCosto1)
                                    .addComponent(lblCostos)
                                    .addComponent(lblCosto))))
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bRealizaTra)
                        .addGap(281, 281, 281))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinea)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addComponent(lblCostoPlacas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCostos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcion1)
                    .addComponent(lblCosto1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpcion2)
                    .addComponent(lblCosto2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostoInfo)
                    .addComponent(lblCosto))
                .addGap(18, 18, 18)
                .addComponent(bRealizaTra)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRealizaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizaTraActionPerformed
        try {
            plaNeg.realizarTramitePlaca(placaDTO);
            ValidacionExitosa validacionExitosa = new ValidacionExitosa();
            validacionExitosa.show();
            dispose();
        } catch (PersistenciaException ex) {
            Logger.getLogger(JTramitaPlaca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bRealizaTraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRealizaTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCosto2;
    private javax.swing.JLabel lblCostoInfo;
    private javax.swing.JLabel lblCostoPlacas;
    private javax.swing.JLabel lblCostos;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumeroPlaca;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblOpcion1;
    private javax.swing.JLabel lblOpcion2;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
