package Forms;

import dto.AutomovilDTO;
import dto.ManejaPlacaDTO;
import dto.PlacaDTO;
import excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.PlacasNegocio;
import recursos.TipoAutomovil;

/**
 *
 * @author Chris
 */
public class JTramitaPlaca extends javax.swing.JFrame {

    private AutomovilDTO autoDTO;
    private PlacaDTO placaDTO;
    private PlacasNegocio plaNeg;
    private ManejaPlacaDTO mPla;

    /**
     * Creates new form JTramitaPlaca
     */
    public JTramitaPlaca(PlacaDTO placaDTO) {
        initComponents();
        this.plaNeg = new PlacasNegocio();
        this.placaDTO = placaDTO;
        this.autoDTO = new AutomovilDTO();
        cargarDatosAutoNuevo();
    }

    public JTramitaPlaca(ManejaPlacaDTO placaDTO) {
        initComponents();
        this.plaNeg = new PlacasNegocio();
        this.mPla = placaDTO;
        this.autoDTO = new AutomovilDTO();
        cargarDatosAutoUsado();
    }

    private void cargarDatosAutoNuevo() {
        String tipoVehiculo;
        String numeroPlaca = plaNeg.generaPlacaNueva();
        String numeroFormateado;

        lblTipo.setText("Nuevo");
        plaNeg.calcularCostoVehiculoNuevo(placaDTO);
        placaDTO.setNumPlaca(numeroPlaca);
        autoDTO = placaDTO.getVehiculo();
        lblNumeroPlaca.setText(placaDTO.getNumPlaca());
        tipoVehiculo = placaDTO.getTipoVehiculo();
        numeroFormateado = String.format("%.2f", placaDTO.getMonto());

        lblColor.setText(autoDTO.getColor());
        lblLinea.setText(autoDTO.getLinea());
        lblModelo.setText(autoDTO.getModelo());
        lblMarca.setText(autoDTO.getMarca());
        lblNumeroSerie.setText(autoDTO.getNumSerie());

        lblCosto.setText("$" + numeroFormateado);

//        switch (tipoVehiculo) {
//            case "Automovil":
//                lblOpcion1.setText("Automóvil nuevo");
//                lblOpcion2.setText("Automóvil usado");
//                break;
//        }
    }

    private void cargarDatosAutoUsado() {
        String tipoVehiculo;
        String numeroPlaca = plaNeg.generaPlacaNueva();
        String numeroFormateado;

        lblTipo.setText("Usado");
        plaNeg.calcularCostoVehiculoUsado(mPla);
        mPla.setNumero(numeroPlaca);
        autoDTO = mPla.getVehiculo();
        lblNumeroPlaca.setText(mPla.getNumero());
        tipoVehiculo = mPla.getTipoVehiculo();
        numeroFormateado = String.format("%.2f", mPla.getMonto());

        lblColor.setText(autoDTO.getColor());
        lblLinea.setText(autoDTO.getLinea());
        lblModelo.setText(autoDTO.getModelo());
        lblMarca.setText(autoDTO.getMarca());
        lblNumeroSerie.setText(autoDTO.getNumSerie());

        lblCosto.setText("$" + numeroFormateado + " MXN");

//        switch (tipoVehiculo) {
//            case "Automovil":
//                lblOpcion1.setText("Automóvil nuevo");
//                lblOpcion2.setText("Automóvil usado");
//                break;
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumeroPlaca = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblOpcion1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblOpcion2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        botonRealizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 174, 92));

        jPanel2.setBackground(new java.awt.Color(18, 234, 207));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Resumen del Tramite");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        botonRegresar.setBackground(new java.awt.Color(117, 117, 117));
        botonRegresar.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        botonRegresar.setText(">");
        botonRegresar.setBorder(null);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel3.setText("Numero de Placa:");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel4.setText("Numero de Serie:");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel5.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel6.setText("Linea:");

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel7.setText("Modelo:");

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel8.setText("Color:");

        lblNumeroPlaca.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblNumeroPlaca.setText("M");

        lblNumeroSerie.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblNumeroSerie.setText("M");

        lblMarca.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        lblMarca.setText("M");

        lblLinea.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblLinea.setText("M");

        lblModelo.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblModelo.setText("M");

        lblColor.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblColor.setText("M");

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel15.setText("Tipo:");

        lblTipo.setFont(new java.awt.Font("Lucida Sans", 2, 20)); // NOI18N
        lblTipo.setText("M");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel17.setText("COSTOS $$");

        lblOpcion1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblOpcion1.setText("Nuevo                $1500");

        lblOpcion2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblOpcion2.setText("Usado                $1000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOpcion2)
                    .addComponent(lblOpcion1)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOpcion1)
                .addGap(18, 18, 18)
                .addComponent(lblOpcion2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel20.setText("Costo a pagar:");

        lblCosto.setFont(new java.awt.Font("Lucida Sans", 1, 20)); // NOI18N
        lblCosto.setText("S");

        botonRealizar.setBackground(new java.awt.Color(175, 244, 198));
        botonRealizar.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        botonRealizar.setText("Realizar");
        botonRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumeroSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumeroPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCosto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(botonRealizar)
                                    .addGap(43, 43, 43)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblNumeroPlaca))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblNumeroSerie))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblMarca))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblLinea)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblModelo)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblColor))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCosto)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTipo)
                    .addComponent(botonRealizar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarActionPerformed
        TipoAutomovil tipo = autoDTO.getTipo();
        try {
            if (tipo == TipoAutomovil.Nuevo) {
                plaNeg.realizarTramitePlaca(placaDTO);
                ValidacionExitosa validacionExitosa = new ValidacionExitosa();
                validacionExitosa.show();
                dispose();
            } else {
                plaNeg.realizarTramitePlaca(mPla);
                ValidacionExitosa validacionExitosa = new ValidacionExitosa();
                validacionExitosa.show();
                dispose();
            }

        } catch (PersistenciaException ex) {
            Logger.getLogger(JTramitaPlaca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonRealizarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        JAgregarCarroForm ca = new JAgregarCarroForm();
        ca.setVisible(true);

        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRealizar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumeroPlaca;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblOpcion1;
    private javax.swing.JLabel lblOpcion2;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
